name: reportr
version: 1.0.0+1
description: A new Flutter module project.
environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  firebase_core: ^2.9.0
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  firebase_auth: ^4.4.0
  image_picker: ^0.8.7+1
  flutter_animate: ^4.1.1+1
  cloud_firestore: ^4.5.0
  uuid: ^3.0.7
  image_picker_android: ^0.8.6+6
  firebase_storage: ^11.1.0
  cached_network_image: ^3.2.3
  path: ^1.8.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  module:
    androidPackage: com.denoic.reportr
    iosBundleIdentifier: com.denoic.reportr
    androidX: true
  uses-material-design: true
